spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/processor
      username: admin
      password: admin
server:
  port: 8888

folderPath: "C:\\Users\\data" #文件夹路径

#所有CAN设备的Id号以及位置数据，英文逗号分隔
canIds: "0x0581,0x0582,0x0583,0x0584,0x0585,0x0586,0x0587"
canDistance: "0,20,40,60,80,100,120"
canNumber: 7

fPass: 0.5 #通带截止频率
fStop: 2 #阻带截止频率
aPass: 1 #通带最大衰减
aStop: 40 #阻带最小衰减
fSample: 50 #采样频率
