spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/processor
      username: admin
      password: admin
server:
  port: 8888

folderPath: "C:\\Users\\01\\myData" #文件夹路径
#fPass: 0.1 #通带截止频率
#fStop: 2 #阻带截止频率
#aPass: 1 #通带最大衰减
#aStop: 40 #阻带最小衰减
#fSample: 50 #采样频率

#所有CAN设备的Id号以及位置数据，英文逗号分隔
canIds: "0x0581,0x0582,0x0583,0x0584,0x0585,0x0586,0x0587,0x0588"
canDistance: "0,11.43,22.86,34.29,45.72,57.15,68.58,80.00"